version: '3'
services:
  web:
    depends_on:
      - database
    build: .
    image: alyssontkd/ambiente-glpi
    container_name: 'dev-glpiv1.0'
    ports:
     - "80:80"
     - "443:443"
     - "8888:8888"
    volumes:
     - /var/www/docker/glpi:/var/www/html/dev.glpi.com.br
     - /var/www/docker/logs/apache2/glpi:/var/log/apache2
    environment:
     - APPLICATION_ENV=development
#Bloco 2: Descomente este trecho e comente o Bloco 1 para compilar a imagem do banco junto com a imagem da aplicação.
    links:
     - database

  database:
   image: mysql:5.7
   container_name: 'database-mysql-glpi'
   command: mysqld --sql_mode=""
   expose:
       - "3306"
   ports:
        - "3306:3306"
   volumes:
        - /var/www/database/mysql/conf.d:/etc/mysql/conf.d
        - /var/www/database/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
        - /var/www/database/mysql/data:/var/lib/mysql
        - /var/www/database/mysql/log:/var/log/
   environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_USER: usr_aplicacao
        MYSQL_PASSWORD: 12345678
        MYSQL_DATABASE: glpi
#Fim do Bloco 2

#Bloco1: O bloco um é um exemplo de como plugar o GLPI a um conteiner de banco já existente.
#Comente este bloco e descomente o Bloco 2 caso queira subir o conteiner de banco de dados junto com o conteiner
#    external_links:
#      - database-mysql_1:mysql
#    networks:
#      - default
#      - databasemysql_default
#networks:
#    databasemysql_default:
#        external:
#            name: databasemysql_default
#Fim do Bloco 1
